name: K6 Load Test

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to load test'
        required: true
        type: string
      duration:
        description: 'Test duration in seconds'
        required: false
        default: '30'
        type: string
      virtual_users:
        description: 'Number of virtual users'
        required: false
        default: '10'
        type: string
      ramp_up:
        description: 'Ramp-up time in seconds'
        required: false
        default: '15'
        type: string
      steady_state:
        description: 'Steady state time in seconds'
        required: false
        default: '30'
        type: string
      ramp_down:
        description: 'Ramp-down time in seconds'
        required: false
        default: '15'
        type: string
      threshold_req_duration:
        description: 'Request duration threshold in ms'
        required: false
        default: '1000'
        type: string
      threshold_req_failed:
        description: 'Request failure rate threshold'
        required: false
        default: '0.01'
        type: string

jobs:
  k6_load_test:
    name: K6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      
      - name: Run K6 Load Test
        run: k6 run .github/workflows/scripts/k6-test.js
        env:
          URL: ${{ github.event.inputs.url }}
          RAMP_UP: ${{ github.event.inputs.ramp_up }}
          STEADY_STATE: ${{ github.event.inputs.steady_state }}
          RAMP_DOWN: ${{ github.event.inputs.ramp_down }}
          VIRTUAL_USERS: ${{ github.event.inputs.virtual_users }}
          THRESHOLD_REQ_DURATION: ${{ github.event.inputs.threshold_req_duration }}
          THRESHOLD_REQ_FAILED: ${{ github.event.inputs.threshold_req_failed }}
      
      - name: List Generated Files
        run: ls -la
      
      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: k6-load-test-report
          path: |
            summary-*.html
            summary-*.json
          retention-days: 30
      
      - name: Add Summary
        run: |
          echo "## K6 Load Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tested URL:** ${{ github.event.inputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "**Virtual Users:** ${{ github.event.inputs.virtual_users }}" >> $GITHUB_STEP_SUMMARY
          echo "**Duration Settings:**" >> $GITHUB_STEP_SUMMARY
          echo "- Ramp-up: ${{ github.event.inputs.ramp_up }}s" >> $GITHUB_STEP_SUMMARY
          echo "- Steady state: ${{ github.event.inputs.steady_state }}s" >> $GITHUB_STEP_SUMMARY
          echo "- Ramp-down: ${{ github.event.inputs.ramp_down }}s" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Please download the HTML report artifact for detailed results." >> $GITHUB_STEP_SUMMARY
