name: Apply terraform plan

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'phase6-7/terraform/**'

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1

jobs:
  apply:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # unsecure, for POC purposes
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # unsecure, for POC purposes
            aws-region: ${{ env.AWS_REGION }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: phase6-7/terraform